config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resources :books do
    member do
      get :delete
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'books'

  def index
    @books = Book.order(:price)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book '#{@book.title}' added successfully."
      redirect_to(books_path)
    else
      flash[:error] = "Book was not added successfully."
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      flash[:notice] = "Book '#{@book.title}' updated successfully."
      redirect_to(books_path)
    else
      flash[:error] = "Book was not updated successfully."
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' destroyed successfully."
    redirect_to(books_path)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :price, :publish_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_collection_helper.rb
module BookCollectionHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/delete.html.erb
<%= link_to books_path do %>
	<i class="fas fa-home fa-3x"></i>
<% end %>

<% @page_title = "Delete" %>

<h1>Delete</h1>

<p>About to Delete the Following Book:</p>

<table>
	<tr>
		<th>Title</th>
		<td><%= @book.title %></td>
	</tr>
	<tr>
		<th>Author</th>
		<td><%= @book.author %></td>
	</tr>
	<tr>
		<th>Genre</th>
		<td><%= @book.genre %></td>
	</tr>
	<tr>
		<th>Price</th>
		<td><%= "$%0.2f" % @book.price %></td>
	</tr>
	<tr>
		<th>Published on</th>
		<td><%= @book.publish_date %></td>
	</tr>
	<tr>
		<th>Added to Database on</th>
		<td><%= @book.created_at %></td>
	</tr>
	<tr>
		<th>Last Updated on</th>
		<td><%= @book.updated_at %></td>
	</tr>
</table>

<%= form_for(@book, :method => 'delete') do |f| %>
	<p>Are you sure?</p>
	<%= f.submit("Delete Book", :class => "btn btn-primary") %>
<% end %>

app/views/books/edit.html.erb
<%= link_to books_path do %>
	<i class="fas fa-home fa-3x"></i>
<% end %>

<% @page_title = "Update a Book" %>

<h1>Update a Book</h1>

<p>Updating <%= @book.title %></p>

<%= form_for(@book) do |f| %>
	<table>
		<tr>
			<th>Title</th>
			<td><%= f.text_field(:title) %></td>
		</tr>
		<tr>
			<th>Author</th>
			<td><%= f.text_field(:author) %></td>
		</tr>
		<tr>
			<th>Genre</th>
			<td><%= f.select(:genre, [['Action and adventure'], ['Alternate history'], ['Anthology'], ['Art/architecture'], ['Autobiography'], ['Biography'], ['Business/economics'], ['Chick lit'], ['Children\'s'], ['Classic '], ['Comic book'], ['Coming-of-age'], ['Cookbook'], ['Crafts/hobbies'], ['Crime'], ['Diary'], ['Dictionary'], ['Drama'], ['Encyclopedia'], ['Fairytale'], ['Fantasy'], ['Graphic novel'], ['Guide'], ['Health/fitness'], ['Historical fiction'], ['History'], ['Home and garden'], ['Horror'], ['Humor'], ['Journal'], ['Math'], ['Memoir'], ['Mystery'], ['Paranormal romance'], ['Philosophy'], ['Picture book'], ['Poetry'], ['Political thriller'], ['Prayer'], ['Religion, spirituality, and new age'], ['Review'], ['Satire'], ['Science'], ['Science fiction'], ['Self help'], ['Short story'], ['Sports and leisure'], ['Suspense'], ['Textbook'], ['Thriller'], ['Travel'], ['True crime'], ['Western'], ['Young adult']]) %></td>
		</tr>
		<tr>
			<th>Price (USD)</th>
			<td><%= f.number_field(:price, :step => 0.01) %></td>
		</tr>
		<tr>
			<th>Publish Date (yyyy-mm-dd)</th>
			<td><%= f.date_field(:publish_date) %></td>
		</tr>
	</table>

	<%= f.submit("Update Book", :class => "btn btn-primary") %>
<% end %>

app/views/books/index.html.erb
<% @page_title = "Home Page" %>

<h1>Home Page</h1>

<p>The books and their functions are below:</p>

<ul>
	<li><i class="fas fa-home"></i> &mdash; Home Page</li>
	<li><i class="fas fa-info-circle"></i> &mdash; Show Details</li>
	<li><i class="fas fa-edit"></i> &mdash; Update a Book</li>
	<li><i class="fas fa-trash"></i> &mdash; Delete</li>
	<li><i class="fas fa-plus-circle"></i> &mdash; Add a Book</li>
</ul>

<table>
	<thead>
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th><strong>Details</strong></th>
			<th><strong>Edit</strong></th>
			<th><strong>Remove</strong></th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
			<tr class="data-row">
				<td><%= book.title %></td>
				<td><%= book.author %></td>
				<td><%= "$%0.2f" % book.price %></td>
				<td>
					<%= link_to book_path(book) do %>
						<i class="fas fa-info-circle"></i>
					<% end %>
				</td>
				<td>
					<%= link_to edit_book_path(book) do %>
						<i class="fas fa-edit"></i>
					<% end %>
				</td>
				<td>
					<%= link_to delete_book_path(book) do %>
						<i class="fas fa-trash"></i>
					<% end %>
				</td>
			</tr>
		<% end %>
		<tr>
			<td>
				<%= link_to new_book_path do %>
					<i class="fas fa-plus-circle"></i>
				<% end %>
			</td>
		</tr>
	</tbody>
</table>

app/views/books/new.html.erb
<%= link_to books_path do %>
	<i class="fas fa-home fa-3x"></i>
<% end %>

<% @page_title = "Add a Book" %>

<h1>Add a Book</h1>

<%= form_for(@book) do |f| %>
	<table>
		<tr>
			<th>Title</th>
			<td><%= f.text_field(:title) %></td>
		</tr>
		<tr>
			<th>Author</th>
			<td><%= f.text_field(:author) %></td>
		</tr>
		<tr>
			<th>Genre</th>
			<td><%= f.select(:genre, [['Action and adventure'], ['Alternate history'], ['Anthology'], ['Art/architecture'], ['Autobiography'], ['Biography'], ['Business/economics'], ['Chick lit'], ['Children\'s'], ['Classic '], ['Comic book'], ['Coming-of-age'], ['Cookbook'], ['Crafts/hobbies'], ['Crime'], ['Diary'], ['Dictionary'], ['Drama'], ['Encyclopedia'], ['Fairytale'], ['Fantasy'], ['Graphic novel'], ['Guide'], ['Health/fitness'], ['Historical fiction'], ['History'], ['Home and garden'], ['Horror'], ['Humor'], ['Journal'], ['Math'], ['Memoir'], ['Mystery'], ['Paranormal romance'], ['Philosophy'], ['Picture book'], ['Poetry'], ['Political thriller'], ['Prayer'], ['Religion, spirituality, and new age'], ['Review'], ['Satire'], ['Science'], ['Science fiction'], ['Self help'], ['Short story'], ['Sports and leisure'], ['Suspense'], ['Textbook'], ['Thriller'], ['Travel'], ['True crime'], ['Western'], ['Young adult']]) %></td>
		</tr>
		<tr>
			<th>Price (USD)</th>
			<td><%= f.number_field(:price, :step => 0.01) %></td>
		</tr>
		<tr>
			<th>Publish Date (yyyy-mm-dd)</th>
			<td><%= f.date_field(:publish_date) %></td>
		</tr>
	</table>

	<%= f.submit("Create Book", :class => "btn btn-primary") %>
<% end %>

app/views/books/show.html.erb
<%= link_to books_path do %>
	<i class="fas fa-home fa-3x"></i>
<% end %>

<% @page_title = "Show Details" %>

<h1>Show Details</h1>

<p><%= @book.title %> by <%= @book.author %>:</p>

<table class="data-inline">
	<tr>
		<th>Title</th>
		<td><%= @book.title %></td>
	</tr>
	<tr>
		<th>Author</th>
		<td><%= @book.author %></td>
	</tr>
	<tr>
		<th>Genre</th>
		<td><%= @book.genre %></td>
	</tr>
	<tr>
		<th>Price</th>
		<td><%= "$%0.2f" % @book.price %></td>
	</tr>
	<tr>
		<th>Published on</th>
		<td><%= @book.publish_date %></td>
	</tr>
	<tr>
		<th>Added to Database on</th>
		<td><%= @book.created_at %></td>
	</tr>
	<tr>
		<th>Last Updated on</th>
		<td><%= @book.updated_at %></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment3RubyOnRailsPulchroxloom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/books.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= @page_title || "Book Collection Application" %></title>
		<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= yield %>
		<% if !flash[:error].blank? %>
			<div class="error">
				<h3>Error</h3>
				<%= flash[:notice] %>
			</div>
		<% end %>
		<% if !flash[:notice].blank? %>
			<div class="notice">
				<h3>Notice</h3>
				<%= flash[:notice] %>
			</div>
		<% end %>
	</body>
</html>